apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: cors-frontend
spec:
  template:
    metadata:
      labels:
        tier: cors-frontend
    spec:
      containers:
      - name: cors-frontend
        # image: my-website
        imagePullPolicy: Always
        image: gcr.io/my-website-169905/cors-frontend:latest
        ports:
        - containerPort: 80
